FROM ubuntu:16.04

RUN apt update
RUN apt install -y \
    build-essential \
    pkg-config \
    cmake \
    git \
    libgtk2.0-dev \
    libgtk2.0-dev \
    pkg-config \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev
